services:
  app:
    container_name: aguia-app
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "7979:7979"
    networks:
      - aguia-network
    volumes:
      - "$PWD:/usr/src/backend/"
  db:
    container_name: aguia-db
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=P@ssw0rd123
      - POSTGRES_DB=backend
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "backend"]
      interval: 10s
      timeout: 60s
      retries: 10

    networks:
      - aguia-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  aguia-network:

volumes:
  postgres_data:
